[package]
name        = "winx-infra"
description = "Adapters concretos (impl de ports) do Winx-KVM: Win32, QUIC, mDNS, cpal, etc."
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
authors.workspace      = true
license.workspace      = true
repository.workspace   = true

[lints]
workspace = true

[dependencies]
winx-domain      = { workspace = true }
winx-protocol    = { workspace = true }
winx-application = { workspace = true }
tokio            = { workspace = true }
async-trait      = { workspace = true }
serde            = { workspace = true }
serde_json       = { workspace = true }
toml             = { workspace = true }
thiserror        = { workspace = true }
anyhow           = { workspace = true }
tracing          = { workspace = true }
time             = { workspace = true }

hex     = { workspace = true }
uuid    = { workspace = true }
keyring = { version = "3", features = ["windows-native"] }
mdns-sd = { workspace = true }
if-addrs = { workspace = true }

quinn          = { workspace = true }
rustls         = { workspace = true }
rcgen          = { workspace = true }
rustls-pemfile = { workspace = true }
x509-parser    = { workspace = true }
ed25519-dalek  = { workspace = true }
sha2           = { workspace = true }
windows          = { workspace = true }
crossbeam-channel = { workspace = true }
arboard           = { workspace = true }

[dev-dependencies]
rand     = { workspace = true }
tempfile = "3"
